### ISSUE TITLE
Nome de arquivos estão imperfeitos quando são encaminhados. 

### ISSUE THREAD

**Issue by d34dfr4m3** [d34dfr4m3/Cl4r4Li1l3#5]
No arquivo **classbot.py** no que se refere à tratamento de nome dos arquivos que seria o processe de pegar o nome do arquivo e colocar num formato amigável está incorreto. 

Segue o bloco de código referente ao tratamento: 
 ```
if filename.find("_") != -1: #replace _ with space
  filename = filename.replace("_", " ")
 ```
#### Primeiro Caso: 
Segue a forma que a Clara faz upload: 

Nome original: 
```
seguranca_fisica.pdf
```
Nome salvo no Channel:
```
File: seguranca fisica
```
Sugestão de Melhoria:
```
Segurança Física
```

#### Segundo Caso: 
Nome Original:
```
Cap2-Vulnerabilidades-Ameacas-riscos.pdf
```
Nome Encaminhado: 
```
Cap2-Vulnerabilidades-Ameacas-Riscos
```

Sugestão de Melhoria: 
```
Cap2 Vulnerabilidades Ameacas Riscos
```

#### Terceiro Caso:
Bloco de código do **classbot.py**
```
filename = file.media.document.attributes[0].file_name.split(".", 1)[0]
```

###### Problema: 
Se o arquivo tiver mais de um ponto no nome, o tratamento fica restrito apenas ao primeiro conjunto, logo um arquivo com o nome: 
``` 
Bla.Blablabla.pdf
```
Teria o tratamento aplicado apenas ao primeiro conjunto, no caso **Bla.**

Thats all folks

**Comment by N1et** [comment]
O **Primeiro caso** já foi resolvido.
O **Segundo Caso**, resolvido. As seguintes linhas foram alteradas/adicionadas: 
Método forwardfile(). Linha 45.
Nova: 
```
if filename.find("_") != -1: #replace _ with space
 filename = filename.replace("_", " ")
if filename.find("-") != -1:
 filename = filename.replace("-", " ")
```
Original:
```
if filename.find("_") != -1: #replace _ with space
 filename = filename.replace("_", " ")
```

**Comment by N1et** [comment]
O **Terceira Caso**, resolvido. As seguintes linhas foram alteradas/adicionadas:
Método forwardfile(). Linha 45
Nova:
```
filename = file.media.document.attributes[0].file_name
filename = filename.replace(".", " ", ( filename.count(".")-1 ) ).split(".")[0]
```
original:
```
filename = file.media.document.attributes[0].file_name.split(".", 1)[0]
```

**Comment by d34dfr4m3** [comment]
Thanks cyberbaby!
